version: '3.8'

services:
  boot-app:
    image: abhinavkumar03/chat-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://ak2711474:X3X62OrsGZqFNIXZ@cluster0.6bxeyy5.mongodb.net/chatapp?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - app-network

  react-service:
    image: abhinavkumar03/chat-frontend:latest
    build:
      context: ../chatapp-frontend
      dockerfile: Dockerfile

    ports:
      - "5173:80"
    networks:
      - app-network



networks:
  app-network:
